/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `SlicePolicyDecision_PccRuleIds`;

DROP TABLE IF EXISTS `SlicePolicyDecision`;

CREATE TABLE `SlicePolicyDecision` (
  `Snssai_Sst` INT NOT NULL,
  `Snssai_Sd` VARCHAR(128) NOT NULL,
  `Snssai_SdIsSet` TINYINT(1) NOT NULL,
  `SnssaiIsSet` TINYINT(1) NOT NULL,
  `PccRuleIdsIsSet` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Snssai_Sst`,
               `Snssai_Sd`,
               `Snssai_SdIsSet`))
 ENGINE=InnoDB;

CREATE TABLE `SlicePolicyDecision_PccRuleIds` (
  `object_id_Sst` INT NOT NULL,
  `object_id_Sd` VARCHAR(128) NOT NULL,
  `object_id_SdIsSet` TINYINT(1) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `SlicePolicyDecision_PccRuleIds_object_id_fk`
    FOREIGN KEY (`object_id_Sst`,
                 `object_id_Sd`,
                 `object_id_SdIsSet`)
    REFERENCES `SlicePolicyDecision` (`Snssai_Sst`,
                                      `Snssai_Sd`,
                                      `Snssai_SdIsSet`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `SlicePolicyDecision_PccRuleIds` (
    `object_id_Sst`,
    `object_id_Sd`,
    `object_id_SdIsSet`);

CREATE INDEX `index_i`
  ON `SlicePolicyDecision_PccRuleIds` (`index`);

