/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `SupiPolicyDecision_PccRuleIds`;

DROP TABLE IF EXISTS `SupiPolicyDecision`;

CREATE TABLE `SupiPolicyDecision` (
  `Supi` VARCHAR(128) NOT NULL PRIMARY KEY,
  `SupiIsSet` TINYINT(1) NOT NULL,
  `PccRuleIdsIsSet` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `SupiPolicyDecision_PccRuleIds` (
  `object_id` VARCHAR(128) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `SupiPolicyDecision_PccRuleIds_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `SupiPolicyDecision` (`Supi`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `SupiPolicyDecision_PccRuleIds` (`object_id`);

CREATE INDEX `index_i`
  ON `SupiPolicyDecision_PccRuleIds` (`index`);

