#!/usr/bin/env bash
# =====================================================================
#                ____      _    _  ______  _   _    _
#               |  _ \    / \  | |/ / ___|| | | |  / \
#               | |_) |  / _ \ | ' /\___ \| |_| | / _ \
#               |  _ <  / ___ \| . \ ___) |  _  |/ ___ \
#               |_| \_\/_/   \_\_|\_\____/|_| |_/_/   \_\
#
#                5G Security for Critical Communications
# =====================================================================
#
# SimulaMet RAKSHA 5G Network Core Scripts
# Copyright (C) 2021-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu


# Random waiting time, since there are probably multiple simultaneous connections!
random-sleep 0 5

# ====== Handle arguments ===================================================
if [ $# -ne 4 ] ; then
   echo >&2 "Usage: $0 server docker_compose_directory docker_compose_file container"
   exit 1
fi

server="$1"
dockerComposeDirectory="$2"
dockerComposeFile="$3"
container="$4"
shift 2
while true ; do
   echo "Connecting to ${container} on ${server} ..."
   ssh -t "${server}" docker compose -f "${dockerComposeDirectory}/${dockerComposeFile}" exec -it "${container}" /bin/bash --login || random-sleep 0 30
done
