services:
    gnbsim:
        container_name: gnbsim
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=242
            - MNC=88
            - GNBID=1
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000031
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=449c4b91aeacd0ace182cf3a5a72bfa1
            - OPc=9245cd6283cc53ce24ac1186a60dee6b
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=yes
            - AMF_FQDN=oai-amf
            - NGAPPeerAddr=0.0.0.0
            - GTPuLocalAddr=0.0.0.0
            - GTPuIFname=eth0
        networks:
            public_net: null
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim2:
        container_name: gnbsim2
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=242
            - MNC=88
            - GNBID=2
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000032
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=449c4b91aeacd0ace182cf3a5a72bfa1
            - OPc=9245cd6283cc53ce24ac1186a60dee6b
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=yes
            - AMF_FQDN=oai-amf
            - NGAPPeerAddr=0.0.0.0
            - GTPuLocalAddr=0.0.0.0
            - GTPuIFname=eth0
        networks:
            public_net: null
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim3:
        container_name: gnbsim3
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=242
            - MNC=88
            - GNBID=3
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000033
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=449c4b91aeacd0ace182cf3a5a72bfa1
            - OPc=9245cd6283cc53ce24ac1186a60dee6b
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=yes
            - AMF_FQDN=oai-amf
            - NGAPPeerAddr=0.0.0.0
            - GTPuLocalAddr=0.0.0.0
            - GTPuIFname=eth0
        networks:
            public_net: null
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim4:
        container_name: gnbsim4
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=242
            - MNC=88
            - GNBID=4
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000034
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=449c4b91aeacd0ace182cf3a5a72bfa1
            - OPc=9245cd6283cc53ce24ac1186a60dee6b
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=yes
            - AMF_FQDN=oai-amf
            - NGAPPeerAddr=0.0.0.0
            - GTPuLocalAddr=0.0.0.0
            - GTPuIFname=eth0
        networks:
            public_net: null
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim5:
        container_name: gnbsim5
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=242
            - MNC=88
            - GNBID=5
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000035
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=449c4b91aeacd0ace182cf3a5a72bfa1
            - OPc=9245cd6283cc53ce24ac1186a60dee6b
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=yes
            - AMF_FQDN=oai-amf
            - NGAPPeerAddr=0.0.0.0
            - GTPuLocalAddr=0.0.0.0
            - GTPuIFname=eth0
        networks:
            public_net: null
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim-fqdn:
        container_name: gnbsim-fqdn
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=242
            - MNC=88
            - GNBID=5
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000035
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=449c4b91aeacd0ace182cf3a5a72bfa1
            - OPc=9245cd6283cc53ce24ac1186a60dee6b
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=yes
            - AMF_FQDN=amf.oai-5gc.eur
            - GTPuIFname=eth0
        networks:
            public_net: null
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        name: demo-oai-public-net
        external: true
