services:
    mysql:
        container_name: "mysql"
        image: dreibh/mysql:latest
        volumes:
            - ./database/simulamet-oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net: null
    oai-udr:
        container_name: "oai-udr"
        image: dreibh/oai-udr:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/simulamet-basic_nrf_config.yaml:/openair-udr/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - mysql
            - oai-nrf
        networks:
            public_net: null
    oai-udm:
        container_name: "oai-udm"
        image: dreibh/oai-udm:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/simulamet-basic_nrf_config.yaml:/openair-udm/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        networks:
            public_net: null
    oai-ausf:
        container_name: "oai-ausf"
        image: dreibh/oai-ausf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/simulamet-basic_nrf_config.yaml:/openair-ausf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        networks:
            public_net: null
    oai-nrf:
        container_name: "oai-nrf"
        image: dreibh/oai-nrf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/simulamet-basic_nrf_config.yaml:/openair-nrf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        networks:
            public_net: null
    oai-amf:
        container_name: "oai-amf"
        image: dreibh/oai-amf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 38412/sctp
        volumes:
            - ./conf/simulamet-basic_nrf_config.yaml:/openair-amf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        networks:
            public_net: null
    oai-smf:
        container_name: "oai-smf"
        image: dreibh/oai-smf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/simulamet-basic_nrf_config.yaml:/openair-smf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        networks:
            public_net: null
    oai-upf:
        container_name: "oai-upf"
        image: dreibh/oai-upf:develop
        expose:
            - 2152/udp
            - 8805/udp
        volumes:
            - ./conf/simulamet-basic_nrf_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net: null
    oai-ext-dn:
        privileged: true
        init: true
        container_name: oai-ext-dn
        image: dreibh/trf-gen-cn5g:latest
        environment:
            - UPF_FQDN=oai-upf
            - UE_NETWORK=12.1.1.0/24
            - USE_FQDN=yes
        healthcheck:
            test: /bin/bash -c "ip r | grep 12.1.1"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net: null
networks:
    public_net:
        driver: macvlan
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.200.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
            parent: vxlan
