services:
    gnbsim-vpp:
        container_name: gnbsim-vpp
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=242
            - MNC=88
            - GNBID=5
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000031
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=449c4b91aeacd0ace182cf3a5a72bfa1
            - OPc=9245cd6283cc53ce24ac1186a60dee6b
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
            - NGAPPeerAddr=192.168.200.132
            - GTPuLocalAddr=192.168.202.141
            - GTPuIFname=eth1
        networks:
            public_net:
                ipv4_address: 192.168.200.141
            public_net_access:
                ipv4_address: 192.168.202.141
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        name: demo-oai-public-net
        external: true
    public_net_access:
        name: oai-public-access
        external: true
