version: '3.8'
services:
    ueransim-gnb:
        privileged: true
        init: true
        container_name: ueransim-gnb
        image: phinetech/ueransim:v3.2.6
        command: nr-gnb -c /home/config-gnb.yaml
        volumes:
            - ./ran-qos/simulamet-oai-cn5g-gnb.yaml:/home/config-gnb.yaml
        networks:
            public_net:
                ipv4_address: 192.168.200.141
            n3_net:
                ipv4_address: 192.168.201.141
    ueransim-ue-5qi-1:
        privileged: true
        init: true
        container_name: ueransim-ue-5qi-1
        image: phinetech/ueransim:v3.2.6
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
        command:
            - bash
            - -c
            - |
                apt install ethtool -y;
                ethtool -K eth0 tx off;
                nr-ue -c /home/config-ue.yaml;
        volumes:
            - ./ran-qos/simulamet-ue-5qi-1.yaml:/home/config-ue.yaml
        depends_on:
            - ueransim-gnb
        networks:
            public_net:
                ipv4_address: 192.168.200.142
    ueransim-ue-5qi-3:
        privileged: true
        init: true
        container_name: ueransim-ue-5qi-3
        image: phinetech/ueransim:v3.2.6
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
        command:
            - bash
            - -c
            - |
                apt install ethtool -y;
                ethtool -K eth0 tx off;
                nr-ue -c /home/config-ue.yaml;
        volumes:
            - ./ran-qos/simulamet-ue-5qi-3.yaml:/home/config-ue.yaml
        depends_on:
            - ueransim-gnb
        networks:
            public_net:
                ipv4_address: 192.168.200.143
networks:
    public_net:
        external:
            name: demo-oai-public-net
    n3_net:
        external:
            name: demo-oai-n3-net
