version: '3.8'
services:
    ueransim:
        container_name: ueransim
        image: rohankharade/ueransim:latest
        privileged: true
        environment:
            - MCC=242
            - MNC=88
            - NCI=0x000000010
            - TAC=0xa000
            - LINK_IP=192.168.200.151
            - NGAP_IP=192.168.200.151
            - GTP_IP=192.168.201.151
            - NGAP_PEER_IP=192.168.200.132
            - SST=222
            - SD=123
            - IGNORE_STREAM_IDS=true
            - NUMBER_OF_UE=1
            - IMSI=242881234500032
            - KEY=449c4b91aeacd0ace182cf3a5a72bfa1
            - OP=9245cd6283cc53ce24ac1186a60dee6b
            - OP_TYPE=OPC
            - AMF_VALUE=8000
            - IMEI=356938035643803
            - IMEI_SV=0035609204079514
            - GNB_IP_ADDRESS=192.168.200.151
            - PDU_TYPE=IPv4
            - APN=default
            - SST_0=222
            - SD_0=123
            - SST_C=222
            - SD_C=123
            - SST_D=222
            - SD_D=123
        networks:
            public_net:
                ipv4_address: 192.168.200.151
            n3_net:
                ipv4_address: 192.168.201.151
        healthcheck:
            test: /bin/bash -c "ifconfig uesimtun0"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net
    n3_net:
        external:
            name: demo-oai-n3-net
