services:
    my5grantester:
        image: my5grantester:latest
        container_name: my5grantester
        privileged: true
        environment:
            NGAP_LOCAL_ADDR: 192.168.200.143
            NGAP_REMOTE_ADDR: 192.168.200.132
            GTPU_LOCAL_ADDR: 192.168.202.143
            MCC: 242
            MNC: 88
            TAC: 00a000
            GNBID: "000003"
            SST_GNB: de
            SST_UE: 222
            SD: "00007b"
            MSIN: "0000000031"
            OPC: 9245cd6283cc53ce24ac1186a60dee6b
            KEY: 449c4b91aeacd0ace182cf3a5a72bfa1
            AMF: 8000
            SQN: 0
            DNN: default
            NUM_UE: 1
        cap_add:
            - NET_ADMIN
        networks:
            public_net:
                ipv4_address: 192.168.200.143
            public_net_access:
                ipv4_address: 192.168.202.143
        healthcheck:
            test: /bin/bash -c "ip addr | grep uetun1"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        name: demo-oai-public-net
        external: true
    public_net_access:
        name: oai-public-access
        external: true
