#!/usr/bin/env bash
# =====================================================================
#                ____      _    _  ______  _   _    _
#               |  _ \    / \  | |/ / ___|| | | |  / \
#               | |_) |  / _ \ | ' /\___ \| |_| | / _ \
#               |  _ <  / ___ \| . \ ___) |  _  |/ ___ \
#               |_| \_\/_/   \_\_|\_\____/|_| |_/_/   \_\
#
#                5G Security for Critical Communications
# =====================================================================
#
# SimulaMet RAKSHA 5G Network Core Scripts
# Copyright (C) 2021-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu

ENC_OPC_KEY="9245cd6283cc53ce24ac1186a60dee6b"   # Operator Provisioning Code (OPC)
ENC_AUTH_KEY="449c4b91aeacd0ace182cf3a5a72bfa1"  # Simcard Authentication Key (K, Ki)

COMPOSITIONS="
   docker-compose-basic-nrf-ebpf.yaml
   docker-compose-basic-nrf-mongodb.yaml
   docker-compose-basic-nrf-qos.yaml
   docker-compose-basic-nrf.yaml
   docker-compose-basic-vpp-nrf.yaml
   docker-compose-basic-vpp-pcf-redirection.yaml
   docker-compose-basic-vpp-pcf-steering.yaml
   docker-compose-basic-vpp-pcf-ulcl.yaml
   docker-compose-gnbsim-ebpf.yaml
   docker-compose-gnbsim-vpp-additional.yaml
   docker-compose-gnbsim-vpp.yaml
   docker-compose-gnbsim.yaml
   docker-compose-mini-nonrf.yaml
   docker-compose-my5grantester-vpp.yaml
   docker-compose-no-privilege.yaml
   docker-compose-oai-rfsim-ebpf.yaml
   docker-compose-omec-gnbsim-vpp.yaml
   docker-compose-pcf-provisioning-api.yaml
   docker-compose-slicing-basic-nrf.yaml
   docker-compose-slicing-ransim.yaml
   docker-compose-ueransim-ebpf.yaml
   docker-compose-ueransim-qos.yaml
   docker-compose-ueransim-vpp.yaml
"

CONFIGS="
   ./omec-gnbsim-config.yaml
   conf/basic_nrf_config_ebpf.yaml
   conf/basic_nrf_config_mongodb.yaml
   conf/basic_nrf_config_qos.yaml
   conf/basic_nrf_config.yaml
   conf/basic_vpp_nrf_config.yaml
   conf/mini_nonrf_config.yaml
   conf/nssf_slice_config.yaml
   conf/pcf_provisioning_config.yaml
   conf/slicing_base_config.yaml
   conf/slicing_slice1_config.yaml
   conf/slicing_slice2_config.yaml
   conf/slicing_slice3_config.yaml
   conf/ulcl_config.yaml
   ran-conf/gnb.conf
   ran-conf/gnb_ebpf.conf
   ran-conf/nr-ue2.conf
   ran-conf/nr-ue.conf
   ran-qos/oai-cn5g-gnb.yaml
   ran-qos/ue-5qi-1.yaml
   ran-qos/ue-5qi-3.yaml
   database/oai_db1.sql
   database/oai_db-basic.sql
   database/oai_db_mongo.js
   database/oai_db2.sql
   database/pcf-provisioning/DnnPolicyDecision.sql
   database/pcf-provisioning/PccRuleODB.sql
   database/pcf-provisioning/QosData.sql
   database/pcf-provisioning/SlicePolicyDecision.sql
   database/pcf-provisioning/SupiPolicyDecision.sql
   database/pcf-provisioning/TrafficControlDataODB.sql
"

for input in ${COMPOSITIONS} ${CONFIGS} ; do
   if [[ "${input}" =~ ^(docker-compose-)(.*)(\.yaml)$ ]] ; then
      output="docker-compose-simulamet-${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
   elif [[ "${input}" =~ ^(.*/)(.*)(\.yaml|\.conf|\.sql|\.js)$ ]] ; then
      output="${BASH_REMATCH[1]}/simulamet-${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
   else
      echo >&2 "ERROR: Unknown file ${input}!"
      exit 1
   fi

   echo "Creating ${output} ..."

   # ====== Modifications for SimulaMet Testbed =============================
   # * Change IP address prefixes
   # * Change MCC to 242 (Norway)
   # * Change MNC to 88, 89, ... (unallocated in Norway)
   # * Change IMSIs accordingly
   # * Set OPC and KI keys
   #   NOTE: We use example keys, but swapped for whatever reason
   #         -> Set placeholder first, then replace them!
   # * Change UEID and SUPI to 242xx12345nnnnn
   sed "${input}" \
       -e "s#192\.168\.70\.#192.168.243.#g" \
       -e "s#192\.168\.71\.#192.168.244.#g" \
       -e "s#192\.168\.72\.#192.168.245.#g" \
       -e "s#192\.168\.73\.#192.168.246.#g" \
       -e "s#192\.168\.74\.#192.168.247.#g" \
       -e "s#192\.168\.75\.#192.168.248.#g" \
       -e "s#192\.168\.76\.#192.168.249.#g" \
       -e "s#\(mcc\|MCC\)\([ =:'\"]*\)\(208\)#\1\2242#g" \
       -e "s#\(mnc\|MNC\)\([ =:'\"]*\)\(95\)#\1\288#g" \
       -e "s#\(mnc\|MNC\)\([ =:'\"]*\)\(93\)#\1\289#g" \
       -e "s#\([Ii]msi\|IMSI\|imsi-\|ueid\|supi\|servingPlmnid\)\([ =:'\"]*\)\(20895\)#\1\224288#g" \
       -e "s#\([Ii]msi\|IMSI\|imsi-\|ueid\|supi\|servingPlmnid\)\([ =:'\"]*\)\(20893\)#\1\224289#g" \
       -e "s#\([Ii]msi\|IMSI\|imsi-\|ueid\|supi\|servingPlmnid\)\([ =:'\"]*\)\(20899\)#\1\224290#g" \
       -e "s#'20895#'24288#g" \
       -e "s#'20893#'24289#g" \
       -e "s#'20899#'24290#g" \
       -e "s#'20894#'24291#g" \
       -e "s#'20892#'24292#g" \
       -e "s#./conf/#./conf/simulamet-#g" \
       -e "s#image: oaisoftwarealliance/#image: dreibh/#g" \
       -e "s#\(0C0A34601D4F07677303652C0462535B\|465b5ce8b199b49faa5f0a2ee238a6bc\|8BAF473F2F8FD09487CCCBD7097C6862\|8BAF473F2F8FD09487CCCBD7097C6862\|fec86ba6eb707ed08905757b1bb44b8f\)#***ENC_AUTH_KEY***#g" \
       -e "s#\(63bfa50ee6523365ff14c1f45f88737d\|cd63cb71954a9f4e48a5994e37a02baf\|c42449363bbad02b66d16bc975d77cc1\|0C0A34601D4F07677303652C0462535B\|8e27b6af0e692e750f32667a3b14605d\)#***ENC_OPC_KEY***#g" \
       -e "s#\*\*\*ENC_AUTH_KEY\*\*\*#${ENC_AUTH_KEY}#g" \
       -e "s#\*\*\*ENC_OPC_KEY\*\*\*#${ENC_OPC_KEY}#g" \
       -e "s#\(24288\|2429[0-9]\)00000#\112345#g" \
       >"${output}"
done

find -type f -name "*simula*" | grep -v make- | xargs grep --color 2089 || true
# grep --color -E "[0-9a-fA-F]{32}" database/simulamet-* || true
