#!/usr/bin/env bash
# =====================================================================
#                ____      _    _  ______  _   _    _
#               |  _ \    / \  | |/ / ___|| | | |  / \
#               | |_) |  / _ \ | ' /\___ \| |_| | / _ \
#               |  _ <  / ___ \| . \ ___) |  _  |/ ___ \
#               |_| \_\/_/   \_\_|\_\____/|_| |_/_/   \_\
#
#                5G Security for Critical Communications
# =====================================================================
#
# SimulaMet RAKSHA 5G Network Core Scripts
# Copyright (C) 2021-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu


REMOTE_DOCKER_COMPOSE_DIRECTORY="/home/nornetpp/src/oai-cn5g-fed/docker-compose"


# ###### Generate tab configurations ########################################
function generate-tabs ()
{
   local proxy="$1"
   local dockerComposeDirectory="$2"
   local dockerComposeFile="$3"
   while read -r container ; do
      if [ "${container}" == '"mysql"' ] ; then
         name="MySQL"
      else
         name="${container^^}"
      fi
      echo "title: ${name};; command: $(realpath access) ${proxy} ${dockerComposeDirectory} ${dockerComposeFile} ${container}"
   done
}


# ###### Main program #######################################################

# ====== Handle arguments ===================================================
if [ $# -lt 2 ] ; then
   echo >&2 "Usage: $0 proxy_server dockerfile [...]"
   exit 1
fi
proxy=$1
shift

# ====== Generate tabs files ================================================
while [ $# -gt 0 ] ; do
   inputFile="$1"
   inputFileBasename="$(basename "$1")"
   outputFile="${inputFile/\.yaml/.tabs}"
   if [ "${inputFile}" == "${outputFile}" ] ; then
      echo >&2 "ERROR: Bad input fule ${inputFile}!"
      exit 1
   fi
   shift

   # Filter with address:
   # yq '.services[] | (.container_name, .networks.public_net.ipv4_address)' \

   echo -e "\e[34mGenerating ${outputFile} from ${inputFile} ...\e[0m"
   yq '.services[].container_name' \
      <"${inputFile}" | \
      tr -d '"' | \
      generate-tabs "${proxy}" "${REMOTE_DOCKER_COMPOSE_DIRECTORY}" "${inputFileBasename}" | \
      sort | tee "${outputFile}"
done
