#!/usr/bin/env bash
# =====================================================================
#                ____      _    _  ______  _   _    _
#               |  _ \    / \  | |/ / ___|| | | |  / \
#               | |_) |  / _ \ | ' /\___ \| |_| | / _ \
#               |  _ <  / ___ \| . \ ___) |  _  |/ ___ \
#               |_| \_\/_/   \_\_|\_\____/|_| |_/_/   \_\
#
#                5G Security for Critical Communications
# =====================================================================
#
# SimulaMet RAKSHA 5G Network Core Scripts
# Copyright (C) 2021-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu

DOCKERHUB="dreibh"
CONTAINERS="
   oaisoftwarealliance/oai-amf:develop
   oaisoftwarealliance/oai-ausf:develop
   oaisoftwarealliance/oai-gnb:develop
   oaisoftwarealliance/oai-nrf:develop
   oaisoftwarealliance/oai-nr-ue:develop
   oaisoftwarealliance/oai-nssf:develop
   oaisoftwarealliance/oai-pcf:develop
   oaisoftwarealliance/oai-smf:develop
   oaisoftwarealliance/oai-udm:develop
   oaisoftwarealliance/oai-udr:develop
   oaisoftwarealliance/oai-upf:develop
   oaisoftwarealliance/oai-upf-vpp:develop
   ubuntu/mysql:latest
   oaisoftwarealliance/trf-gen-cn5g:latest
   oaisoftwarealliance/ims:latest
"
# CONTAINERS="ubuntu/mysql:latest"


declare -A CORE_FUNCTIONS=(
   ["AMF"]="Access and Mobility Management Function (AMF)"
   ["AUSF"]="Authentication Server Management Function (AUSF)"
   ["LMF"]="Location Management Function (LMF)"
   ["NEF"]="Network Exposure Function (NEF)"
   ["NRF"]="Network Repository Function (NRF)"
   ["NSSF"]="Network Slicing Selection Function (NSSF)"
   ["NWDAF"]="Network Data Analytics Function (NWDAF)"
   ["PCF"]="Policy Control Function (PCF)"
   ["SMF"]="Session Management Function (SMF)"
   ["UDM"]="Unified Data Management (UDM)"
   ["UDR"]="Unified Data Repository (UDR)"
   ["UPF"]="User Plane Function (UPF)"
   ["UPF-VPP"]="User Plane Function with VPP-Based Implementation (UPF-VPP)"
   ["UDSF"]="Unstructured Data Storage Function (UDSF)"
   ["GNB"]="gNodeB (GNB)"
   ["NR-UE"]="New Radio User Equipment (NR-UE)"
   ["TRF-GEN-CN5G"]="Traffic Generator for OAI 5G Core Network (TRF-GEN-CN5G)"
   ["MYSQL"]="MySQL Subscriber Database"
   ["IMS"]="IP Multimedia Subsystem"
)

for fromContainerWithTag in ${CONTAINERS} ; do
   modifiedContainerWithTag="${fromContainerWithTag/*\/}"
   modifiedContainer="${modifiedContainerWithTag/:*/}"
   modifiedContainerTag="${modifiedContainerWithTag/*:/}"
   descriptionKey="${modifiedContainer/oai-/}"
   descriptionKey="${descriptionKey^^}"
   # echo "descriptionKey=${descriptionKey}"

   coreFunctionLabel="SimulaMet ${modifiedContainer^^}"
   coreFunctionDescription="This is the ${CORE_FUNCTIONS[${descriptionKey}]}"

   echo "${coreFunctionLabel} \"${coreFunctionDescription}\": ${fromContainerWithTag} -> ${modifiedContainer}"

   cat >"Dockerfile-${modifiedContainer}" <<EOF
FROM ${fromContainerWithTag}

COPY simulamet/50-core-function /etc/system-info.d/
COPY simulamet/60-raksha        /etc/system-info.d/

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    EDITOR="joe"

RUN sed -e 's/^FUNCTION_LABEL=.*$/FUNCTION_LABEL="${coreFunctionLabel}"/' \
        -e 's/^FUNCTION_DESCRIPTION=.*$/FUNCTION_DESCRIPTION="${coreFunctionDescription}"/' \
        -i /etc/system-info.d/50-core-function && \
    apt update && \
    DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y software-properties-common gnupg && \
    apt-add-repository -y ppa:dreibh/ppa && \
    DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y && \
    echo "y" | DEBIAN_FRONTEND=noninteractive unminimize && \
    DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
       bash-completion \
       bwm-ng \
       curl \
       git \
       hipercontracer \
       htop joe less man \
       iputils-ping \
       netperfmeter \
       popularity-contest \
       rsplib-tools \
       subnetcalc \
       sysstat \
       tcpdump \
       tree \
       td-system-info \
       traceroute \
       tsctp \
       tshark \
       ytree && \
    DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y plocate || \
       DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y mlocate && \
    sed -e 's/^PARTICIPATE="no"/PARTICIPATE="yes"/' -i /etc/popularity-contest.conf && \
    sed -e '/^SUBMITURLS=""/d' -e 's/^#SUBMITURLS=/SUBMITURLS=/' -i /usr/share/popularity-contest/default.conf && \
    /etc/cron.daily/popularity-contest && \
    updatedb && \
    apt clean
EOF

   # cat "Dockerfile-${modifiedContainer}"
   docker buildx build \
      --push \
      --tag "${DOCKERHUB}/${modifiedContainer}:${modifiedContainerTag}" \
      --file "Dockerfile-${modifiedContainer}" \
      .

   echo "Test with: docker run --rm -it ${DOCKERHUB}/${modifiedContainer}:${modifiedContainerTag} bash --login"
done
