#!/usr/bin/env bash
# =====================================================================
#                ____      _    _  ______  _   _    _
#               |  _ \    / \  | |/ / ___|| | | |  / \
#               | |_) |  / _ \ | ' /\___ \| |_| | / _ \
#               |  _ <  / ___ \| . \ ___) |  _  |/ ___ \
#               |_| \_\/_/   \_\_|\_\____/|_| |_/_/   \_\
#
#                5G Security for Critical Communications
# =====================================================================
#
# SimulaMet RAKSHA 5G Network Core Scripts
# Copyright (C) 2021-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu


# NOTE:
# Turn OFF setting General -> Remember window size
# Otherwise, Konsole is going to ignore the size settings here!


# ###### Main program #######################################################

# ====== Handle arguments ===================================================
if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 tab_file [...]"
   exit 1
fi

# ====== Handle arguments ===================================================
while [ $# -gt 0 ] ; do
   inputFile="$1"
   shift

   if [ ! -e "${inputFile}" ] ; then
      echo >&2 "ERROR: ${inputFile} not found!"
      exit 1
   fi

   # NOTE: Use --hold option for debugging --tabs-from-file!
   konsole \
      --separate \
      -p ShowTerminalSizeHint=true -p TerminalColumns=160 -p TerminalRows=32 \
      -p ColorScheme=WhiteOnBlack \
      --tabs-from-file "${inputFile}" \
      -e date &

   if [ $# -gt 0 ] ; then
      random-sleep 0 5
   fi
done
