#!/usr/bin/env bash
# =====================================================================
#                ____      _    _  ______  _   _    _
#               |  _ \    / \  | |/ / ___|| | | |  / \
#               | |_) |  / _ \ | ' /\___ \| |_| | / _ \
#               |  _ <  / ___ \| . \ ___) |  _  |/ ___ \
#               |_| \_\/_/   \_\_|\_\____/|_| |_/_/   \_\
#
#                5G Security for Critical Communications
# =====================================================================
#
# SimulaMet RAKSHA 5G gNodeB Run Script
# Copyright (C) 2021-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu


# Assuming Ettus N310!

ping -c3 -i0.2 192.168.200.138   # AMF
ping -c3 -i0.2 192.168.10.2      # Ettus via fibre0
ping -c3 -i0.2 192.168.20.2      # Ettus via fibre1
ping -c3 -i0.2 10.132.17.40      # Ettus via copper

cd ~/src/openairinterface5g
source oaienv
cd cmake_targets/ran_build/build


# Simple:
# sudo ./nr-softmodem -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.band78.sa.fr1.106PRB.2x2.usrpn310.conf --gNBs.[0].min_rxtxtime 6 --usrp-tx-thread-config 1 --thread-pool 1,2,3,4


# Allow coredumps:
sudo bash -c "ulimit -c unlimited ; exec ./nr-softmodem -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.band78.sa.fr1.106PRB.2x2.usrpn310.conf --gNBs.[0].min_rxtxtime 6 --usrp-tx-thread-config 1 --thread-pool 1,2,3,4"


# Some testing with real-time scheduling and priority:
# sudo chrt --fifo -r 99 ./nr-softmodem -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.band78.sa.fr1.106PRB.2x2.usrpn310.conf --gNBs.[0].min_rxtxtime 6 --usrp-tx-thread-config 1 --thread-pool 1,2,3,4


# Non-root run:
# See tuning_and_security.md -> https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/69962ef9abcac0431505207ccb37b41a893f0d6c/doc/tuning_and_security.md:
# sudo setcap cap_sys_nice+ep ./nr-softmodem
# sudo setcap cap_ipc_lock+ep ./nr-softmodem
# sudo setcap cap_sys_nice+ep ./nr-uesoftmodem
# sudo setcap cap_ipc_lock+ep ./nr-uesoftmodem
# sudo setcap cap_net_admin+ep ./nr-uesoftmodem
# sudo sysctl -w net.core.wmem_max=62500000
# sudo sysctl -w net.core.rmem_max=62500000
# ulimit -c unlimited
# ./nr-softmodem -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.band78.sa.fr1.106PRB.2x2.usrpn310.conf --gNBs.[0].min_rxtxtime 6 --usrp-tx-thread-config 1 --thread-pool 1,2,3,4
